#!/usr/bin/env bash

set -Eeuo pipefail
umask 077

PACKAGE_ROOT="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck source=lib/common.sh
source "$PACKAGE_ROOT/runtime/lib/common.sh"

background=1
case "${1:-}" in
  --background) shift ;;
  --foreground) background=0; shift ;;
esac

package_validate_tree "$PACKAGE_ROOT"
package_load_metadata "$PACKAGE_ROOT"
package_create_runtime_directories "$PACKAGE_ROOT"

host_platform="$(package_host_platform)"
host_architecture="$(package_host_architecture)"
[[ "$host_platform" == "$WENZWORK_PACKAGE_PLATFORM" ]] ||
  package_die "package target is $WENZWORK_PACKAGE_PLATFORM but this host is $host_platform"
[[ "$host_architecture" == "$WENZWORK_PACKAGE_ARCHITECTURE" ]] ||
  package_die "package architecture is $WENZWORK_PACKAGE_ARCHITECTURE but this host is $host_architecture"

package_initialize_environment "$PACKAGE_ROOT"
if (( PACKAGE_ENVIRONMENT_CREATED == 1 )); then
  package_die "Edit $PACKAGE_ROOT/.env, then run start.sh again."
fi

chmod 0755 "$PACKAGE_ROOT/start.sh" "$PACKAGE_ROOT/upgrade.sh" "$PACKAGE_ROOT/stop.sh"
[[ ! -f "$PACKAGE_ROOT/backup.sh" ]] || chmod 0755 "$PACKAGE_ROOT/backup.sh"
find "$PACKAGE_ROOT/bin" -maxdepth 1 -type f -exec chmod 0755 {} +
[[ -f "$PACKAGE_ROOT/.env" && ! -L "$PACKAGE_ROOT/.env" ]] ||
  package_die "environment file must be a regular file and must not be a symbolic link"
chmod 0600 "$PACKAGE_ROOT/.env"

package_load_env "$PACKAGE_ROOT/.env"
package_apply_component_defaults "$PACKAGE_ROOT"
# The token is used only by upgrade.sh and must not reach a service process.
unset GITHUB_ACCESS_TOKEN GH_TOKEN GITHUB_TOKEN

generate_host_dependency_password() {
  local value
  [[ -r /dev/urandom ]] || package_die "/dev/urandom is required to generate dependency credentials"
  value="$(LC_ALL=C od -An -N24 -tx1 /dev/urandom | tr -d '[:space:]')"
  [[ "$value" =~ ^[0-9a-f]{48}$ ]] || package_die "could not generate a secure dependency credential"
  printf '%s' "$value"
}

HOST_SETUP_USES_INITIAL_VALUES=0

validate_host_environment_state() {
  local template="$PACKAGE_ROOT/config/host.env.example"
  local initial_setup configured_setup setting initial_value configured_value
  [[ -f "$template" && ! -L "$template" ]] ||
    package_die "Host initial environment template is missing or unsafe: $template"
  initial_setup="$(package_read_env_value "$template" SYSTEM_SETUP_COMPLETED 2>/dev/null || true)"
  [[ "$initial_setup" == false ]] ||
    package_die "Host initial environment template must set SYSTEM_SETUP_COMPLETED=false"
  if ! configured_setup="$(package_read_env_value "$PACKAGE_ROOT/.env" SYSTEM_SETUP_COMPLETED 2>/dev/null)"; then
    configured_setup="$initial_setup"
  fi
  case "$configured_setup" in
    false) HOST_SETUP_USES_INITIAL_VALUES=1 ;;
    true) HOST_SETUP_USES_INITIAL_VALUES=0 ;;
    *) package_die "SYSTEM_SETUP_COMPLETED must be true or false in .env" ;;
  esac

  if (( HOST_SETUP_USES_INITIAL_VALUES == 0 )); then
    return 0
  fi
  for setting in SYSTEM_ADMIN_EMAIL SYSTEM_ADMIN_PASSWORD; do
    if ! initial_value="$(package_read_env_value "$template" "$setting" 2>/dev/null)"; then
      initial_value=''
    fi
    if ! configured_value="$(package_read_env_value "$PACKAGE_ROOT/.env" "$setting" 2>/dev/null)"; then
      configured_value=''
    fi
    [[ -n "$configured_value" && "$configured_value" != "$initial_value" ]] ||
      package_die "$setting still has its initial value; edit .env before the first start"
  done
}

append_host_dependency_url() {
  local file="$PACKAGE_ROOT/.env" setting="$1" value="$2"
  [[ -f "$file" && ! -L "$file" ]] ||
    package_die "environment file must remain a regular file while dependencies are initialized"
  [[ "$setting" == DATABASE_URL || "$setting" == REDIS_URL ]] ||
    package_die "unsupported managed dependency setting: $setting"
  if package_read_env_value "$file" "$setting" >/dev/null 2>&1; then
    package_die "refusing to replace existing $setting in .env"
  fi
  [[ "$value" != *$'\n'* && "$value" != *$'\r'* ]] ||
    package_die "generated dependency URL contains an invalid character"
  # .env belongs to the operator. Append each previously absent generated value
  # after its container is created so comments, advanced settings, hard links,
  # and the file inode stay intact and the new container credential is durable.
  if [[ "$setting" == DATABASE_URL ]]; then
    printf '\n# Generated by WenzWork managed dependency initialization.\n' >> "$file" ||
      package_die "could not append the managed dependency section to .env"
  fi
  printf '%s=%s\n' "$setting" "$value" >> "$file" ||
    package_die "could not append $setting to .env"
  chmod 0600 "$file"
}

provision_host_dependencies() {
  local database_password redis_password reply attempt
  command -v docker >/dev/null 2>&1 ||
    package_die "Docker is required when DATABASE_URL or REDIS_URL is not configured"

  ! docker container inspect wenzwork-postgres >/dev/null 2>&1 ||
    package_die "wenzwork-postgres already exists but DATABASE_URL is missing; recover its credential or remove the stale container"
  database_password="$(generate_host_dependency_password)"
  package_log "Starting the managed PostgreSQL container..."
  docker run -d --name wenzwork-postgres --restart unless-stopped \
    -e POSTGRES_USER=wenzwork -e "POSTGRES_PASSWORD=$database_password" -e POSTGRES_DB=wenzwork \
    -p 127.0.0.1:54328:5432 -v wenzwork-postgres-data:/var/lib/postgresql/data \
    postgres:17-alpine >/dev/null
  DATABASE_URL="postgres://wenzwork:$database_password@127.0.0.1:54328/wenzwork?sslmode=disable"
  append_host_dependency_url DATABASE_URL "$DATABASE_URL"
  export DATABASE_URL

  ! docker container inspect wenzwork-redis >/dev/null 2>&1 ||
    package_die "wenzwork-redis already exists but REDIS_URL is missing; recover its credential or remove the stale container"
  redis_password="$(generate_host_dependency_password)"
  package_log "Starting the managed Redis container..."
  docker run -d --name wenzwork-redis --restart unless-stopped \
    -p 127.0.0.1:63798:6379 -v wenzwork-redis-data:/data redis:8-alpine \
    redis-server --appendonly yes --requirepass "$redis_password" >/dev/null
  REDIS_URL="redis://:$redis_password@127.0.0.1:63798/0"
  append_host_dependency_url REDIS_URL "$REDIS_URL"
  export REDIS_URL

  for ((attempt = 1; attempt <= 60; attempt++)); do
    docker exec wenzwork-postgres pg_isready -U wenzwork -d wenzwork >/dev/null 2>&1 && break
    sleep 1
  done
  docker exec wenzwork-postgres pg_isready -U wenzwork -d wenzwork >/dev/null 2>&1 ||
    package_die "managed PostgreSQL did not become ready"
  for ((attempt = 1; attempt <= 60; attempt++)); do
    reply="$(docker exec -e "REDISCLI_AUTH=$redis_password" wenzwork-redis \
      redis-cli -h 127.0.0.1 -p 6379 ping 2>/dev/null || true)"
    [[ "$reply" == PONG ]] && break
    sleep 1
  done
  [[ "$reply" == PONG ]] || package_die "managed Redis did not become ready"
}

initialize_host() {
  local database_url='' redis_url='' database_present=0 redis_present=0 status initialize_admin=0
  if database_url="$(package_read_env_value "$PACKAGE_ROOT/.env" DATABASE_URL 2>/dev/null)"; then
    database_present=1
  fi
  if redis_url="$(package_read_env_value "$PACKAGE_ROOT/.env" REDIS_URL 2>/dev/null)"; then
    redis_present=1
  fi
  if [[ -n "$database_url" && -n "$redis_url" ]]; then
    DATABASE_URL="$database_url"
    REDIS_URL="$redis_url"
    export DATABASE_URL REDIS_URL
    package_log "Database and Redis are configured in .env; skipping managed dependency creation."
  elif (( HOST_SETUP_USES_INITIAL_VALUES == 0 )); then
    package_die "completed Host configuration must retain non-empty DATABASE_URL and REDIS_URL; restore the existing .env"
  elif [[ -n "$database_url" || -n "$redis_url" ]]; then
    package_die "configure DATABASE_URL and REDIS_URL together, or leave both empty for managed Docker services"
  elif (( database_present == 1 || redis_present == 1 )); then
    package_die "remove empty DATABASE_URL/REDIS_URL entries for managed Docker services, or configure both values"
  else
    package_log "Database and Redis are absent from .env; running first-start dependency initialization."
    provision_host_dependencies
  fi

  for setting in DATABASE_URL REDIS_URL SYSTEM_ADMIN_EMAIL; do
    [[ -n "${!setting:-}" ]] || package_die "$setting must be set in .env"
  done
  [[ -d "$PACKAGE_ROOT/migrations" ]] || package_die "Host migrations are missing"
  package_log "Applying Host database migrations..."
  (cd "$PACKAGE_ROOT" && "$(package_binary_path "$PACKAGE_ROOT" wenzwork-migrate)" up)
  status="$(cd "$PACKAGE_ROOT" && "$(package_binary_path "$PACKAGE_ROOT" wenzwork-admin)" bootstrap status)"
  status="${status##*$'\n'}"
  case "$status" in
    uninitialized)
      [[ -n "${SYSTEM_ADMIN_EMAIL:-}" && -n "${SYSTEM_ADMIN_PASSWORD:-}" ]] ||
        package_die "set SYSTEM_ADMIN_EMAIL and SYSTEM_ADMIN_PASSWORD in .env, then run start.sh again"
      initialize_admin=1
      ;;
    initialized$'\t'*) package_log "Host administrator is already initialized." ;;
    *) package_die "unexpected Host bootstrap status: $status" ;;
  esac
  if (( initialize_admin == 1 )); then
    package_log "Creating the first Host administrator..."
    (cd "$PACKAGE_ROOT" && \
      BOOTSTRAP_ADMIN_EMAIL="$SYSTEM_ADMIN_EMAIL" \
      BOOTSTRAP_ADMIN_PASSWORD="$SYSTEM_ADMIN_PASSWORD" \
      BOOTSTRAP_ADMIN_DISPLAY_NAME="${SYSTEM_ADMIN_DISPLAY_NAME:-WenzWork Administrator}" \
      "$(package_binary_path "$PACKAGE_ROOT" wenzwork-admin)" bootstrap)
  fi
}

if [[ "$WENZWORK_PACKAGE_COMPONENT" == host ]]; then
  validate_host_environment_state
  initialize_host
  package_load_env "$PACKAGE_ROOT/.env"
  package_apply_component_defaults "$PACKAGE_ROOT"
  unset GITHUB_ACCESS_TOKEN GH_TOKEN GITHUB_TOKEN
fi

case "$WENZWORK_PACKAGE_COMPONENT" in
  host)
    executable="$(package_binary_path "$PACKAGE_ROOT" wenzwork-api)"
    arguments=("$@")
    ;;
  relay)
    executable="$(package_binary_path "$PACKAGE_ROOT" wenzwork-relay-server)"
    arguments=("$@")
    ;;
  device-agent)
    executable="$(package_binary_path "$PACKAGE_ROOT" wenzwork-device-agent)"
    arguments=(serve "$@")
    ;;
  *) package_die "unknown package component: $WENZWORK_PACKAGE_COMPONENT" ;;
esac

pid_file="$PACKAGE_ROOT/runtime/pids/wenzwork.pid"
log_file="$PACKAGE_ROOT/logs/wenzwork-$WENZWORK_PACKAGE_COMPONENT.log"
[[ -f "$executable" ]] || package_die "service executable is missing: $executable"
mkdir -p -- "$PACKAGE_ROOT/logs"

if [[ -f "$pid_file" ]]; then
  package_log "Stopping the previous $WENZWORK_PACKAGE_COMPONENT instance before startup..."
  "$PACKAGE_ROOT/stop.sh"
fi

if (( background == 0 )); then
  cd "$PACKAGE_ROOT"
  exec "$executable" "${arguments[@]}"
fi

(
  cd "$PACKAGE_ROOT"
  nohup "$executable" "${arguments[@]}" >> "$log_file" 2>&1 </dev/null &
  printf '%s\n' "$!" > "$pid_file"
)
sleep 1
pid="$(tr -d '[:space:]' < "$pid_file")"
kill -0 "$pid" 2>/dev/null || package_die "$WENZWORK_PACKAGE_COMPONENT exited during startup; inspect $log_file"
package_log "$WENZWORK_PACKAGE_COMPONENT started as PID $pid. Log: $log_file"
